### ISSUE TITLE
(15) Standard Catan Grid Generator

### ISSUE THREAD

**Issue by W3D3** [W3D3/SettlersOfCatan#1]
A standard catan grid is 5 rows with
- 3 Hexes
- 4 Hexes
- 5 Hexes
- 4 Hexes
- 3 Hexes

**Comment by W3D3** [comment]
https://github.com/Hexworks/hexameter

Das wär a gute Library für den Task. 👍

**Comment by W3D3** [comment]
Some more Hexagon Tools: https://github.com/martelogan/island-settlement-boardgame-prototype/tree/master/app/src/main/java/com/catandroid/app/common/components/utilities/hex_grid_utils

**Comment by Thraunig** [comment]
![spielfeld](https://user-images.githubusercontent.com/37068082/38493882-0f8420a0-3bf4-11e8-9f2c-248c37a01cd0.png)


So schaut das Spielfeld mal aus, Hafen mach i jez glei dazu

**Comment by W3D3** [comment]
hübsch 👍 
is des basierend auf meiner Hexagons library oder is des einfach hardgecodet?

**Comment by W3D3** [comment]
Merged in master already in 45c629357991f2c42eccab9dcf50d3dc47bb000d
