### ISSUE TITLE
Trade with Player

### ISSUE THREAD

**Issue by creatio-ex-nihilo** [W3D3/SettlersOfCatan#28]

**Comment by creatio-ex-nihilo** [comment]
@W3D3, @Waldbursche 
Könnte einer von euch mal den branch trade auschecken und nachsehen ob ihr ne Ahnung habt, warum die App unter nem Emulator läuft, aber nicht auf nem Endgerät?
Die lässt sich nämlich nicht mal öffnen, sondern shutted sofort down ohne jegliche Fehlermeldung (oder ersichtlichen Grund im Log) und so lässt sich das Senden über das network schwer (bis garnicht, keine Ahnung xD) testen.
Danke so oder so 👍

**Comment by W3D3** [comment]
I schau mal obs bei mir auch auftritt 🤔

**Comment by W3D3** [comment]
I glaub du hast des Gradle aware make vergessen vorm deploy:

![image](https://user-images.githubusercontent.com/1103924/41501709-b23d9cc8-71a9-11e8-986f-eba38794fd10.png)

Bei mir gehts ganz normal:
![image](https://user-images.githubusercontent.com/1103924/41501728-1a38c550-71aa-11e8-86df-7e082fc3a3eb.png)

Trading habi jetz nicht getestet, aber geht ganz normal bis jetzt 👍

**Comment by creatio-ex-nihilo** [comment]
ok, das mit dem Gradle-aware make hab ich nicht gewusst, danke für die Info.
Na dann bin ich froh, dass ich da nicht ein paar Stunden daran verschwendet habe *hust* xD

**Comment by creatio-ex-nihilo** [comment]
hat aber übrigens auch nichts geändert, aber komischerweise geht es von meinem laptop aus schon o.O ?
ich bin verwirrt xD

**Comment by W3D3** [comment]
Ja des passiert komischerweise immer komplett randomly wenn man branch wechselt. Amfoch hin und wieder checken.

>
>
